### ISSUE TITLE
User should be able to see a page listing all the talks with links to presentations and videos

### ISSUE THREAD

**Issue by mark-adams** [pytexas/PyTexasWeb#23]
@pizzapanther, what do you think about adding a section called "Talks" that pulls the same information used to construct "Schedule" and gives a single page list of all the talks with links to the slides and videos?

This would probably involve adding a column to store a link to the video (since I'm guessing that there is not one currently since there aren't any links showing up on the talk pages) but it seems quite doable.

If you're game, I'll submit a PR.

**Comment by pizzapanther** [comment]
Actually I was just thinking about adding a "video link" to the Session model so we can do something like that. The backend model stuff is in a separate module here:

https://github.com/pizzapanther/TwoSpaces/blob/master/twospaces/conference/models.py#L191

If you want to add that sounds great. Probably needs an API view also because the schedule api is structured by day and room, and this just needs a simple list.

https://github.com/pizzapanther/TwoSpaces/blob/master/twospaces/conference/api1_views.py

Then we just need to add a frontend module in this repo.

**Comment by mark-adams** [comment]
This is done: https://www.pytexas.org/2015/videos
